### ISSUE TITLE
Why only obtain the energy info but not any hopping info after running the ml-tsh script?  

### ISSUE THREAD

**Issue by Yotta-private** [q-posev/ml-tsh#1]
I want to reproduce the  original results of the ml-tsh paper, using the dataset (https://zenodo.org/records/4266393);
but i can only obtain the  result, as bellow image:
![屏幕截图 2024-06-22 155703](https://github.com/q-posev/ml-tsh/assets/66995265/ea6df4c8-fa24-447c-99da-efa92e4e1167)

next,  when i step to run your plot script, could not gain the info (such as, curr_st, and gs etc.)

so what is wrong ? and how to fix this issue? or can you provide me your raw data and scripts? 

Thanks!

**Comment by q-posev** [comment]
Hello @Yotta-private,

I am not sure I understand your issue. You only show a header of your output so it can be that the trajectory that you run has not reached the hopping point yet. Do you see some hopping events when you run it longer? Did you make sure that all pre-trained SchNet models are present on your computer and loaded by the script?

Also, to reproduce your issue I need to know at least the initial conditions and the command line options that you use.

For the plotting issue, can you elaborate?

**Comment by Yotta-private** [comment]
Sorry, I didn't state my problem clearly.

(1) the schnet models applied from the webpage (https://zenodo.org/records/4266393), i used the 'best_model_s2' and 'best_model_s3' as the trained model; and want to reproduce a 2state prediction task; the important other parameters (n_md=4000, step_md=0.25, hop_type=lz, flag_es=3 (init) );  but i see  hopping events occurs (print "Attempted hop according to BL at 3079 2 0.015837424631406805"), is it right ?


However, i still do not understand how to using your plotting scripts.
(2) I noticed that your plotting scripts have mentioned columns name ['time', 'cur_st','gs'], what is the meaning of the cur_st and gs, or can you provide me a example tsh file to correct my input file ?

Sorry for bother you again! Thanks very much !

**Comment by q-posev** [comment]
1) Yes, as the output says the hopping attempt has occurred. However the hop can still sometimes be rejected if it is a "frustrated" one. When the true hop occurs, you should see in the output that the current state (last column) has changed from 3 to 2.

2) I see the problem now. Indeed, the `plot-tsh-occs.py` is not compatible out of the box with your output. However, it can be easily modified and essentially what you need to change is the call to the CSV reader. In the original script curr-state is an integer number corresponding to the current state - last column in your case, gs is the ground state energy which you don't have so can be omitted. Also, the ml-tsh script prints two hopping probabilities (columns last-1 and last-2) which you can omit too.
NB: the plotting scripts should be executed for an ensemble of trajectories, not for a single one.

This work has been performed 4 years ago and unfortunately I no longer have access to all scripts..

Just out of curiosity, do you also work with phenanthrene?

**Comment by YuYaoYang2333** [comment]
(1) Thanks! I fixed all issues accroding to your suggestions!

(2) Yep, I just want to test the  efficiency of TSH combined with schnet training model, so firstly, phenanthrene was chose to be a start point due to your pre-tranined schnet model.

Thanks for your advice! Best wishes !
